/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.retailer;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import SystemModels.ClientOrder.ClientOrder;
import SystemModels.ClientOrder.ClientOrderDirectory;
import SystemModels.EcoSystem;
import SystemModels.Inventory.InventoryDirectory;
import SystemModels.Inventory.Item;
import SystemModels.User.Client.Client;
import SystemModels.User.Customer.Resident;

/**
 *
 * @author Vennela Bandla
 */
public class RetailerProfileItemForSaleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RetailerProfileItemForSaleJPanel
     */
    JPanel jpanel9;
    private EcoSystem ecosystem;
    private Client client;
    private ArrayList<Item> itemsAddedToCart;
    public RetailerProfileItemForSaleJPanel(JPanel RetailerProfileItemForSale, EcoSystem ecosystem, Client client) {
        initComponents();
        this.ecosystem = ecosystem;
        this.client = client;
//        welcomeLabel.setText(this.resident.getFullName());
        this.RetailerItemsForSaleJPanel = RetailerProfileItemForSale;
        this.itemsAddedToCart = new ArrayList<>();
        this.populateTable();
    }
    
    
    
    private void populateTable() {
      
        DefaultTableModel model = (DefaultTableModel) retailtableData.getModel();
        model.setRowCount(0);
        for (Item itemsToPopulate : ecosystem.getInventoryDirectory().getInventoryByStatus(Item.ItemStatus.READY_FOR_SALE)){
            if(itemsToPopulate.getType() != Item.ItemType.REFURB){
                continue;
            }
            Object[] data = new Object[6];
            data[0] = itemsToPopulate;
            data[1] = itemsToPopulate.getCategory();
            data[2] = itemsToPopulate.getSubCategory();
            data[3] = itemsToPopulate.getMake();
            data[4] = itemsToPopulate.getModel();
            data[5] = itemsToPopulate.getPrice();
            model.addRow(data);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RetailerItemsForSaleJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        retailtableData = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderSummaryTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPurchaseOrder = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radioBtnCash = new javax.swing.JRadioButton();
        radioBtnBankTransfer = new javax.swing.JRadioButton();
        radioBtnPayPal = new javax.swing.JRadioButton();

        setLayout(new java.awt.CardLayout());

        RetailerItemsForSaleJPanel.setBackground(new java.awt.Color(0, 102, 102));

        retailtableData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        retailtableData.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        retailtableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Computer Parts", "Applicance Type", "Make", "Model", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        retailtableData.setGridColor(new java.awt.Color(255, 255, 255));
        retailtableData.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane1.setViewportView(retailtableData);

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(51, 51, 51)));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel9.setText("Select an Item");
        jLabel9.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Order Summary");

        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(51, 51, 51)));

        OrderSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(OrderSummaryTable);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/us_dollar_24px.png"))); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/price_tag_18px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalField)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash_48px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cash");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bank_transfer_48px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Internet Banking");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paypal_48px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PayPal");

        btnPurchaseOrder.setBackground(new java.awt.Color(204, 255, 204));
        btnPurchaseOrder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnPurchaseOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPurchaseOrderMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PURCHASE NOW");

        javax.swing.GroupLayout btnPurchaseOrderLayout = new javax.swing.GroupLayout(btnPurchaseOrder);
        btnPurchaseOrder.setLayout(btnPurchaseOrderLayout);
        btnPurchaseOrderLayout.setHorizontalGroup(
            btnPurchaseOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPurchaseOrderLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        btnPurchaseOrderLayout.setVerticalGroup(
            btnPurchaseOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPurchaseOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAddToCart.setBackground(new java.awt.Color(204, 255, 204));
        btnAddToCart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, null, null));
        btnAddToCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddToCartMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_shopping_cart_24px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Checkout cart");

        javax.swing.GroupLayout btnAddToCartLayout = new javax.swing.GroupLayout(btnAddToCart);
        btnAddToCart.setLayout(btnAddToCartLayout);
        btnAddToCartLayout.setHorizontalGroup(
            btnAddToCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddToCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAddToCartLayout.setVerticalGroup(
            btnAddToCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddToCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddToCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        radioBtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RetailerItemsForSaleJPanelLayout = new javax.swing.GroupLayout(RetailerItemsForSaleJPanel);
        RetailerItemsForSaleJPanel.setLayout(RetailerItemsForSaleJPanelLayout);
        RetailerItemsForSaleJPanelLayout.setHorizontalGroup(
            RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                        .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(radioBtnBankTransfer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(radioBtnCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnPayPal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        RetailerItemsForSaleJPanelLayout.setVerticalGroup(
            RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                        .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtnPayPal)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                        .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RetailerItemsForSaleJPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RetailerItemsForSaleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radioBtnCash)
                                        .addComponent(radioBtnBankTransfer)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))))
                        .addContainerGap(150, Short.MAX_VALUE))))
        );

        add(RetailerItemsForSaleJPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToCartMouseClicked
        // TODO add your handling code here:
        Item itemSelected = (Item) retailtableData.getValueAt(retailtableData.getSelectedRow(), 0);
        DefaultTableModel table = (DefaultTableModel) OrderSummaryTable.getModel();
        table.setRowCount(0);
        this.itemsAddedToCart.add(itemSelected);
        int totalPriceInCart = 0;
        for(Item item : this.itemsAddedToCart){
                Object[] data = new Object[2];
                data[0] = item.getSubCategory();
                data[1] = item.getPrice();
                System.out.println("Price cart:"+item.getPrice());
                table.addRow(data);
                table.setRowCount(table.getRowCount());
                totalPriceInCart+=item.getPrice();
        }
        
        totalField.setText(String.valueOf(totalPriceInCart));
        
       
    }//GEN-LAST:event_btnAddToCartMouseClicked

    private void btnPurchaseOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPurchaseOrderMouseClicked
        // TODO add your handling code here:
        ClientOrder newOrder = new ClientOrder(this.client);
        for(Item item : this.itemsAddedToCart){
            item.setStatus(Item.ItemStatus.BLOCKED_FOR_ORDER);
            System.out.println("Item Type"+item.getType());
            newOrder.addItem(item);
            if(radioBtnCash.isSelected()){
                newOrder.getClient().setPaymenttype(Client.paymentType.CASH_ON_DELIVERY);
            }
            else if(radioBtnBankTransfer.isSelected()){
                newOrder.getClient().setPaymenttype(Client.paymentType.BANK_TRANSFER);
            }
            else if(radioBtnPayPal.isSelected()){
                newOrder.getClient().setPaymenttype(Client.paymentType.PAYPAL);
            }
            
        }
        // Add ClientOrder to client order directory
        this.ecosystem.getClientOrderDirectory().addBooking(newOrder);
        totalField.setText("");
        radioBtnCash.setSelected(false);
        radioBtnBankTransfer.setSelected(false);
        radioBtnPayPal.setSelected(false);
        JOptionPane.showMessageDialog(null, "Order Placed Successfully!");
        this.itemsAddedToCart = new ArrayList<>();
        this.populateTable();
        totalField.setText("");
        DefaultTableModel table = (DefaultTableModel) OrderSummaryTable.getModel();
        table.setRowCount(0);
        radioBtnBankTransfer.setSelected(false);
        radioBtnCash.setSelected(false);
        radioBtnPayPal.setSelected(false);
    }//GEN-LAST:event_btnPurchaseOrderMouseClicked

    private void radioBtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnCashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderSummaryTable;
    private javax.swing.JPanel RetailerItemsForSaleJPanel;
    private javax.swing.JPanel btnAddToCart;
    private javax.swing.JPanel btnPurchaseOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioBtnBankTransfer;
    private javax.swing.JRadioButton radioBtnCash;
    private javax.swing.JRadioButton radioBtnPayPal;
    private javax.swing.JTable retailtableData;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
