/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.managementdivision.ManagementDivisionProfileMainJPanel;
import UserInterface.sysadmin.SystemAdminLoginProfile;
import UserInterface.logistics.LogisticsProfileMainJPanel;
import UserInterface.qualitycontrolinspector.QCMainLoginJPanel;
import UserInterface.resident.LoginProfileJPanel;
import UserInterface.retailer.RecyclerLoginJPanel;
import UserInterface.retailer.RetailerLoginMainJPanel;
import UserInterface.sysadmin.SysadminLoginMJPanel;
import UserInterface.technician.TechnicianLoginJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import SystemModels.DB4OUtil.DB4OUtil;
import SystemModels.EcoSystem;
import SystemModels.Roles.ClientRole;
import SystemModels.Roles.InventoryManagerRole;
import SystemModels.Roles.LogisticsManRole;
import SystemModels.Roles.QCInspectorRole;
import SystemModels.Roles.ResidentRole;
import SystemModels.Roles.Role;
import SystemModels.Roles.SystemAdminRole;
import SystemModels.Roles.TechnicianRole;
import SystemModels.User.Client.Client;
import SystemModels.User.Customer.Resident;
import SystemModels.User.Employee.LogisticsMan;
import SystemModels.User.Employee.OperationsManager;
import SystemModels.User.Employee.QCInspector;
import SystemModels.User.Employee.Technician;
import SystemModels.User.UserAccount;


/**
 *
 * @author kalle
 */
public class MainJPanel extends javax.swing.JPanel {
    private static JPanel userProcessContainer;
    
    private EcoSystem ecosystem;
    private DB4OUtil db4oUtil;
    

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        db4oUtil = DB4OUtil.getInstance();
        this.ecosystem = db4oUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_login = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblsignup1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSignUpRetailer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblsignup2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();

        setLayout(new java.awt.CardLayout());

        mainJpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainJpanel.setPreferredSize(new java.awt.Dimension(1460, 850));
        mainJpanel.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign In");
        jLabel3.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");

        usernameTxtField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 118, 102)));
        usernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login_base.png"))); // NOI18N
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));

        lblsignup1.setBackground(new java.awt.Color(204, 255, 204));
        lblsignup1.setFont(new java.awt.Font("Castellar", 1, 28)); // NOI18N
        lblsignup1.setText("Welcome to CPRS!");
        lblsignup1.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Don't have an account?");

        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_signup_base.png"))); // NOI18N
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Are you a Client?");

        btnSignUpRetailer.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUpRetailer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnSignUpRetailer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpRetailerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpRetailerMouseEntered(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reatiler_signup_48px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SIGN UP");

        javax.swing.GroupLayout btnSignUpRetailerLayout = new javax.swing.GroupLayout(btnSignUpRetailer);
        btnSignUpRetailer.setLayout(btnSignUpRetailerLayout);
        btnSignUpRetailerLayout.setHorizontalGroup(
            btnSignUpRetailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignUpRetailerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btnSignUpRetailerLayout.setVerticalGroup(
            btnSignUpRetailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignUpRetailerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSignUpRetailerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblsignup2.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        lblsignup2.setForeground(new java.awt.Color(255, 255, 255));
        lblsignup2.setText("(Computer Parts Recycling System)");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSignup)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(35, 35, 35))))
                            .addComponent(lblsignup1)
                            .addComponent(lblsignup2)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnSignUpRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblsignup1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsignup2)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignup)
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(btnSignUpRetailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 118, 102)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btn_login)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1862, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btn_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainJpanel.add(jPanel2, "card2");

        add(mainJpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtFieldActionPerformed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        String username = usernameTxtField.getText();
        String password = new String(PasswordField.getPassword());
        UserAccount userAccount = this.ecosystem.getUserAccountDirectory().authenticateUser(username, password);
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "Invalid login credentials!");
            return;
        }
        Role role  = userAccount.getRole();
        if (role instanceof ResidentRole) {
            Resident resident = this.ecosystem.getCustomerDirectory().getResidentByUserAccount(userAccount);
            LoginProfileJPanel indivProfileLoginJpanel = new LoginProfileJPanel(mainJpanel, this.ecosystem, resident);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("profileIndividual", indivProfileLoginJpanel);
            layout.next(mainJpanel);
        } else if (role instanceof SystemAdminRole) {
            SysadminLoginMJPanel systemAdminLogin = new SysadminLoginMJPanel(mainJpanel, this.ecosystem);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("Sysadmin", systemAdminLogin);
            layout.next(mainJpanel);
        } else if (role instanceof LogisticsManRole) {
            LogisticsMan logMan = this.ecosystem.getEmployeeDirectory().getLogisticsManByUserAccount(userAccount);
            LogisticsProfileMainJPanel logisticsprofilemain = new LogisticsProfileMainJPanel(mainJpanel, this.ecosystem, logMan);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("LogisticsPanel", logisticsprofilemain);
            layout.next(mainJpanel);
            layout.next(mainJpanel);
        } else if (role instanceof InventoryManagerRole) {
            OperationsManager manager = this.ecosystem.getEmployeeDirectory().getManagerByUserAccount(userAccount);
            ManagementDivisionProfileMainJPanel managementDivisionprofilemain = new ManagementDivisionProfileMainJPanel(mainJpanel, this.ecosystem, manager);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("OperationsManagerPanel", managementDivisionprofilemain);
            layout.next(mainJpanel);
        } else if (role instanceof QCInspectorRole) {
            QCInspector qcinspector = this.ecosystem.getEmployeeDirectory().getQCInspectorByUserAccount(userAccount);
            QCMainLoginJPanel qcAdminMainPanel = new QCMainLoginJPanel(mainJpanel, ecosystem, qcinspector);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("SysadminQCMain", qcAdminMainPanel);
            layout.next(mainJpanel);
        } else if (role instanceof TechnicianRole) {
            Technician technician = this.ecosystem.getEmployeeDirectory().getTechnicanByUserAccount(userAccount);
            TechnicianLoginJPanel systemAdminLogin = new TechnicianLoginJPanel(mainJpanel, ecosystem, technician);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("SysadminTechnician", systemAdminLogin);
            layout.next(mainJpanel);
        } else if (role instanceof ClientRole) {
            Client client = this.ecosystem.getClientDirectory().getClientByUserAccount(userAccount);
            
            if(client.getClienttype() == Client.clientType.RETAILER){
                if(client.isVerified()){
                    RetailerLoginMainJPanel systemAdminRetailClient = new RetailerLoginMainJPanel(mainJpanel, this.ecosystem, client);
                CardLayout layout = (CardLayout) mainJpanel.getLayout();
                mainJpanel.add("SysadminRetailClient", systemAdminRetailClient);
                layout.next(mainJpanel);
                }
                else{
                    usernameTxtField.setText("");
                    PasswordField.setText("");
                    JOptionPane.showMessageDialog(this, "Client is not Verified!");
                }
                
            }
            else if(client.getClienttype() == Client.clientType.RECYCLER){
                if(client.isVerified()){
                    RecyclerLoginJPanel systemAdminRecycler = new RecyclerLoginJPanel(mainJpanel, ecosystem, client);
                    CardLayout layout = (CardLayout) mainJpanel.getLayout();
                    mainJpanel.add("systemAdminRecycler", systemAdminRecycler);
                    layout.next(mainJpanel);
                }
                else{
                    usernameTxtField.setText("");
                    PasswordField.setText("");
                    JOptionPane.showMessageDialog(this, "Client is not Verified!");
                }
                
            }
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        // TODO add your handling code here:
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login_base.png")));
    }//GEN-LAST:event_btn_loginMouseExited

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        // TODO add your handling code here:
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login_onhover.png")));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        // TODO add your handling code here:
        SignupJPanel signupJPanel = new SignupJPanel(mainJpanel, ecosystem);
        CardLayout layout = (CardLayout) mainJpanel.getLayout();
        mainJpanel.add("signup", signupJPanel);

        layout.next(mainJpanel);

    }//GEN-LAST:event_btnSignupMouseClicked

    private void btnSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseEntered
        // TODO add your handling code here:
        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_signup_onhover.png")));
    }//GEN-LAST:event_btnSignupMouseEntered

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        // TODO add your handling code here:
        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_signup_base.png")));
    }//GEN-LAST:event_btnSignupMouseExited

    private void btnSignUpRetailerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpRetailerMouseClicked
        // TODO add your handling code here:
        SignUpRetailerJPanel clientSignUp = new SignUpRetailerJPanel(mainJpanel, ecosystem);
        CardLayout layout = (CardLayout) mainJpanel.getLayout();
        mainJpanel.add("ClientSignUp", clientSignUp);
        layout.next(mainJpanel);

    }//GEN-LAST:event_btnSignUpRetailerMouseClicked

    private void btnSignUpRetailerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpRetailerMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSignUpRetailerMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel btnSignUpRetailer;
    private javax.swing.JLabel btnSignup;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblsignup1;
    private javax.swing.JLabel lblsignup2;
    private javax.swing.JPanel mainJpanel;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
