/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.managementdivision.ManagementDivisionProfileMainJPanel;
import UserInterface.sysadmin.SystemAdminLoginProfile;
import UserInterface.logistics.LogisticsProfileMainJPanel;
import UserInterface.qualitycontrolinspector.QCMainLoginJPanel;
import UserInterface.resident.LoginProfileJPanel;
import UserInterface.retailer.RecyclerLoginJPanel;
import UserInterface.retailer.RetailerLoginMainJPanel;
import UserInterface.technician.TechnicianLoginJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import SystemModels.DB4OUtil.DB4OUtil;
import SystemModels.EcoSystem;
import SystemModels.Roles.ClientRole;
import SystemModels.Roles.InventoryManagerRole;
import SystemModels.Roles.LogisticsManRole;
import SystemModels.Roles.QCInspectorRole;
import SystemModels.Roles.ResidentRole;
import SystemModels.Roles.Role;
import SystemModels.Roles.SystemAdminRole;
import SystemModels.Roles.TechnicianRole;
import SystemModels.User.Customer.Resident;
import SystemModels.User.Employee.LogisticsMan;
import SystemModels.User.Employee.OperationsManager;
import SystemModels.User.UserAccount;
import UserInterface.sysadmin.SysadminLoginMJPanel;
import SystemModels.User.Client.Client;
import SystemModels.User.Employee.QCInspector;
import SystemModels.User.Employee.Technician;


/**
 *
 * @author kalle
 */
public class MainJFrame extends javax.swing.JFrame {
    private static JPanel userProcessContainer;
    
    private EcoSystem ecosystem;
    private DB4OUtil db4oUtil;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        db4oUtil = DB4OUtil.getInstance();
        this.ecosystem = db4oUtil.retrieveSystem();
        this.setSize(1510, 930);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_login = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblsignup1 = new javax.swing.JLabel();
        lblsignup2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainJpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainJpanel.setPreferredSize(new java.awt.Dimension(1460, 850));
        mainJpanel.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign In");
        jLabel3.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");

        usernameTxtField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 118, 102)));
        usernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login_base.png"))); // NOI18N
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        lblsignup1.setBackground(new java.awt.Color(204, 255, 204));
        lblsignup1.setFont(new java.awt.Font("Castellar", 1, 28)); // NOI18N
        lblsignup1.setText("Welcome to CPRS!");
        lblsignup1.setOpaque(true);

        lblsignup2.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        lblsignup2.setForeground(new java.awt.Color(255, 255, 255));
        lblsignup2.setText("(Computer Parts Recycling System)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblsignup1)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblsignup2)
                        .addGap(91, 91, 91))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblsignup1)
                .addGap(18, 18, 18)
                .addComponent(lblsignup2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(65, 118, 102)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(usernameTxtField)
                                .addComponent(jLabel4)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(btn_login)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_login)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        mainJpanel.add(jPanel2, "card2");

        getContentPane().add(mainJpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1460, 850));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bluelight.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1980, 1100));

        setSize(new java.awt.Dimension(1932, 1115));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtFieldActionPerformed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        // TODO add your handling code here:
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login_onhover.png")));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        // TODO add your handling code here:
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login_base.png")));
    }//GEN-LAST:event_btn_loginMouseExited

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        String username = usernameTxtField.getText();
        String password = new String(PasswordField.getPassword());
        UserAccount userAccount = this.ecosystem.getUserAccountDirectory().authenticateUser(username, password);
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "Invalid login credentials!");
            return;
        }
        Role role  = userAccount.getRole();
        if (role instanceof ResidentRole) {
            Resident resident = this.ecosystem.getCustomerDirectory().getResidentByUserAccount(userAccount);
            LoginProfileJPanel indivProfileLoginJpanel = new LoginProfileJPanel(mainJpanel, this.ecosystem, resident);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("profileIndividual", indivProfileLoginJpanel);
            layout.next(mainJpanel);
        } else if (role instanceof SystemAdminRole) {
            SysadminLoginMJPanel systemAdminLogin = new SysadminLoginMJPanel(mainJpanel, this.ecosystem);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("Sysadmin", systemAdminLogin);
            layout.next(mainJpanel);
        } else if (role instanceof LogisticsManRole) {
            LogisticsMan logMan = this.ecosystem.getEmployeeDirectory().getLogisticsManByUserAccount(userAccount);
            LogisticsProfileMainJPanel logisticsprofilemain = new LogisticsProfileMainJPanel(mainJpanel, this.ecosystem, logMan);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("LogisticsPanel", logisticsprofilemain);
            layout.next(mainJpanel);
            layout.next(mainJpanel);
        } else if (role instanceof InventoryManagerRole) {
            OperationsManager manager = this.ecosystem.getEmployeeDirectory().getManagerByUserAccount(userAccount);
            ManagementDivisionProfileMainJPanel managementDivisionprofilemain = new ManagementDivisionProfileMainJPanel(mainJpanel, this.ecosystem, manager);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("OperationsManagerPanel", managementDivisionprofilemain);
            layout.next(mainJpanel);
        } else if (role instanceof QCInspectorRole) {
            QCInspector qcinspector = this.ecosystem.getEmployeeDirectory().getQCInspectorByUserAccount(userAccount);
            QCMainLoginJPanel qcAdminMainPanel = new QCMainLoginJPanel(mainJpanel, ecosystem, qcinspector);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("SysadminQCMain", qcAdminMainPanel);
            layout.next(mainJpanel);
        } else if (role instanceof TechnicianRole) {
            Technician technician = this.ecosystem.getEmployeeDirectory().getTechnicanByUserAccount(userAccount);
            TechnicianLoginJPanel systemAdminLogin = new TechnicianLoginJPanel(mainJpanel, ecosystem, technician);
            CardLayout layout = (CardLayout) mainJpanel.getLayout();
            mainJpanel.add("SysadminTechnician", systemAdminLogin);
            layout.next(mainJpanel);
        } else if (role instanceof ClientRole) {
            Client client = this.ecosystem.getClientDirectory().getClientByUserAccount(userAccount);
            
            if(client.getClienttype() == Client.clientType.RETAILER){
                if(client.isVerified()){
                RetailerLoginMainJPanel systemAdminRetailClient = new RetailerLoginMainJPanel(mainJpanel, ecosystem, client);
                CardLayout layout = (CardLayout) mainJpanel.getLayout();
                mainJpanel.add("SysadminRetailClient", systemAdminRetailClient);
                layout.next(mainJpanel);
                }
                else{
                    usernameTxtField.setText("");
                    PasswordField.setText("");
                    JOptionPane.showMessageDialog(this, "Client is not Verified!");
                }
            }
            else if(client.getClienttype() == Client.clientType.RECYCLER){
                if(client.isVerified()){
                RecyclerLoginJPanel systemAdminRecycler = new RecyclerLoginJPanel(mainJpanel, ecosystem, client);
                CardLayout layout = (CardLayout) mainJpanel.getLayout();
                mainJpanel.add("systemAdminRecycler", systemAdminRecycler);
                layout.next(mainJpanel);
                }
                else{
                    usernameTxtField.setText("");
                    PasswordField.setText("");
                    JOptionPane.showMessageDialog(this, "Client is not Verified!");
                }
            }
            
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame(userProcessContainer).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblsignup1;
    private javax.swing.JLabel lblsignup2;
    private javax.swing.JPanel mainJpanel;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
