/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.logistics;

import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import SystemModels.EcoSystem;
import SystemModels.Inventory.Item;
import SystemModels.User.Employee.LogisticsMan;
import SystemModels.Work.ClientDropoff;

/**
 *
 * @author kalle
 */
public class LogisticsProfileDropOffHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsProfileDropOffHistoryJPanel
     */
    
    JPanel jpanel20;
    EcoSystem ecosystem;
    LogisticsMan logisticsMan;
    public LogisticsProfileDropOffHistoryJPanel(JPanel LogiHistDropOff, EcoSystem ecosystem, LogisticsMan logisticsMan) {
        initComponents();
        
        this.LogisticsDropOffJPanel = LogiHistDropOff;
        this.ecosystem = ecosystem;
        this.logisticsMan = logisticsMan;
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogisticsDropOffJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblscheddropoffs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        LogisticsDropOffJPanel.setBackground(new java.awt.Color(0, 102, 102));

        tblscheddropoffs.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tblscheddropoffs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Retailer", "Request Time", "Resolve Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblscheddropoffs);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Past Drop-Off Order History");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout LogisticsDropOffJPanelLayout = new javax.swing.GroupLayout(LogisticsDropOffJPanel);
        LogisticsDropOffJPanel.setLayout(LogisticsDropOffJPanelLayout);
        LogisticsDropOffJPanelLayout.setHorizontalGroup(
            LogisticsDropOffJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsDropOffJPanelLayout.createSequentialGroup()
                .addGroup(LogisticsDropOffJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogisticsDropOffJPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LogisticsDropOffJPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        LogisticsDropOffJPanelLayout.setVerticalGroup(
            LogisticsDropOffJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsDropOffJPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        add(LogisticsDropOffJPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblscheddropoffs.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        model.setRowCount(0);
        for(ClientDropoff dropOff : this.ecosystem.getWorkRequestDirectory().getDropoffByLogisticMan(this.logisticsMan)){
            Object[] data = new Object[4];
            data[0] = dropOff.getId();
            data[1] = dropOff.getClientOrder().getClient().getFullName();
            data[2] = dropOff.getRequestDate().format(formatter);
            data[3] = dropOff.getResolveDate() == null ? "" : dropOff.getResolveDate().format(formatter);
            model.addRow(data);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogisticsDropOffJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblscheddropoffs;
    // End of variables declaration//GEN-END:variables
}
