/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.logistics;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import SystemModels.CustomerBooking.InventoryBooking;
import SystemModels.EcoSystem;
import SystemModels.Inventory.Item;
import SystemModels.User.Employee.LogisticsMan;
import SystemModels.User.Employee.QCInspector;
import SystemModels.Work.InventoryPickup;
import SystemModels.Work.QCInspection;
import SystemModels.Work.WorkRequest;

/**
 *
 * @author kalle
 */
public class LogisticsProfileSchedulePickupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsProfileSchedulePickupJPanel
     */
    JPanel jpanel77;
    EcoSystem ecosystem;
    LogisticsMan logisticsMan;
    InventoryPickup activePickup;
    public LogisticsProfileSchedulePickupJPanel(JPanel LogisticsSchedulePickupJPanel, EcoSystem ecosystem, LogisticsMan logisticsMan) {
        initComponents();
        this.LogisticsSchedulePickUpMain = LogisticsSchedulePickupJPanel;
        this.ecosystem = ecosystem;
        this.logisticsMan = logisticsMan;
        this.activePickup = this.ecosystem.getWorkRequestDirectory().getActivePickup(logisticsMan);
      
        this.populateTable();
         if (this.activePickup == null) {
            JOptionPane.showMessageDialog(null, "No active pickup at this point of time");
        }
         else{
             if (this.activePickup.getStatus() == InventoryPickup.RequestStatus.ONGOING) pickUpJButton.setEnabled(false);
         }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogisticsSchedulePickUpMain = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        residentName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        residentAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        residentContactInfo = new javax.swing.JTextField();
        pickUpJButton = new javax.swing.JButton();
        markDeliveredJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblscheddropoffs = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        LogisticsSchedulePickUpMain.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("Schedule Pickup");
        jLabel4.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Pending Order");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Resident :");

        residentName.setEditable(false);
        residentName.setBackground(new java.awt.Color(255, 255, 255));
        residentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(205, 223, 245)));
        residentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentNameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Resident Address :");

        residentAddress.setEditable(false);
        residentAddress.setBackground(new java.awt.Color(255, 255, 255));
        residentAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(205, 223, 245)));

        jLabel9.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact Info :");

        residentContactInfo.setEditable(false);
        residentContactInfo.setBackground(new java.awt.Color(255, 255, 255));
        residentContactInfo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(205, 223, 245)));

        pickUpJButton.setBackground(new java.awt.Color(204, 255, 204));
        pickUpJButton.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        pickUpJButton.setText("Pick-Up");
        pickUpJButton.setBorderPainted(false);
        pickUpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickUpJButtonActionPerformed(evt);
            }
        });

        markDeliveredJButton.setBackground(new java.awt.Color(204, 255, 204));
        markDeliveredJButton.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        markDeliveredJButton.setText("Mark Delivered");
        markDeliveredJButton.setBorderPainted(false);
        markDeliveredJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDeliveredJButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblscheddropoffs.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tblscheddropoffs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Computer Parts", "Appliance Type", "Item Make", "Item Model", "Year of Manufacture", "Weight", "Condition", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblscheddropoffs);

        javax.swing.GroupLayout LogisticsSchedulePickUpMainLayout = new javax.swing.GroupLayout(LogisticsSchedulePickUpMain);
        LogisticsSchedulePickUpMain.setLayout(LogisticsSchedulePickUpMainLayout);
        LogisticsSchedulePickUpMainLayout.setHorizontalGroup(
            LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                            .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                                    .addGap(337, 337, 337)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11))
                                    .addGap(36, 36, 36)))
                            .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                                    .addComponent(residentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pickUpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(markDeliveredJButton))
                                .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                                    .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(residentName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(residentContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        LogisticsSchedulePickUpMainLayout.setVerticalGroup(
            LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(residentName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(residentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LogisticsSchedulePickUpMainLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(markDeliveredJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickUpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(LogisticsSchedulePickUpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residentContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        add(LogisticsSchedulePickUpMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pickUpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickUpJButtonActionPerformed
        this.activePickup.setStatus(WorkRequest.RequestStatus.ONGOING);
        this.activePickup.getInventoryBooking().getItems().forEach(item -> {
            item.setStatus(Item.ItemStatus.PROCURED);
        });
        JOptionPane.showMessageDialog(null, "Booking marked as pickedup");
        this.populateTable();
    }//GEN-LAST:event_pickUpJButtonActionPerformed

    private void markDeliveredJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDeliveredJButtonActionPerformed
        this.activePickup.setStatus(WorkRequest.RequestStatus.COMPLETED);
        
        // assign items to QC
        for (Item item: this.activePickup.getInventoryBooking().getItems()) {
            QCInspector qc = this.ecosystem.getWorkRequestDirectory().getQCtoAssign();
            QCInspection inpection = new QCInspection(item, qc);
            this.ecosystem.getWorkRequestDirectory().addQCInspection(inpection);
            item.setStatus(Item.ItemStatus.IN_QC);
            this.ecosystem.getWorkRequestDirectory().increaseqcInspectionAssignmentCount(qc);
        }
        
        this.activePickup.getLogisticsMan().setAvailable(true);
        InventoryBooking booking = this.ecosystem.getBookingDirectory().getNextPendingBooking();
        if (booking != null) {
            InventoryPickup pickup = new InventoryPickup(booking);
            pickup.setLogisticsMan(this.logisticsMan);
            this.logisticsMan.setAvailable(false);
            booking.setAssigned(true);
            this.ecosystem.getWorkRequestDirectory().addInventoryPickup(pickup);
            JOptionPane.showMessageDialog(null, "Booking successfully delivered, new booking assigned");
            this.activePickup = pickup;
            this.populateTable();
            return;
        }
        
        
        JOptionPane.showMessageDialog(null, "Booking successfully delivered");
        this.populateTable();
    }//GEN-LAST:event_markDeliveredJButtonActionPerformed

    private void residentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residentNameActionPerformed
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblscheddropoffs.getModel();
        model.setRowCount(0);
        if (this.activePickup == null) return;
        
        residentName.setText(this.activePickup.getInventoryBooking().getResident().getFullName());
        residentAddress.setText(this.activePickup.getInventoryBooking().getResident().getAddress());
        residentContactInfo.setText(this.activePickup.getInventoryBooking().getResident().getPhone());
        
        for (Item item: this.activePickup.getInventoryBooking().getItems()) {
            Object[] row = new Object[8];
            row[0] = item.getCategory();
            row[1] = item.getSubCategory();
            row[2] = item.getMake();
            row[3] = item.getModel();
            row[4] = item.getManufactureYear();
            row[5] = item.getWeightApprox();
            row[6] = item.getCondition();
            row[7] = item.getStatus();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogisticsSchedulePickUpMain;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markDeliveredJButton;
    private javax.swing.JButton pickUpJButton;
    private javax.swing.JTextField residentAddress;
    private javax.swing.JTextField residentContactInfo;
    private javax.swing.JTextField residentName;
    private javax.swing.JTable tblscheddropoffs;
    // End of variables declaration//GEN-END:variables
}
