/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.resident;

import UserInterface.MainJPanel;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import SystemModels.CustomerBooking.InventoryBooking;
import SystemModels.DB4OUtil.DB4OUtil;
import SystemModels.EcoSystem;
import SystemModels.Inventory.Item;
import SystemModels.User.Customer.Resident;

/**
 *
 * @author Pranav Kashyap Komanduri
 */
public class BookingHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndiBookingHistoryJPanel
     */
    private JPanel jpanel8;
    private EcoSystem ecosystem;
    private Resident resident;
    public BookingHistoryJPanel(JPanel JPanelIndBookingDetailsMain, EcoSystem ecosystem, Resident resident) {
        initComponents();
        this.JPanelIndBookingDetailsMain = JPanelIndBookingDetailsMain;
        this.ecosystem = ecosystem;
        this.resident = resident;
        welcomeLabel.setText(this.resident.getFullName());
        this.populateTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelIndBookingDetailsMain = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        lbldropoffheader = new javax.swing.JLabel();
        bookingidlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPickUpBookingDetails = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtbookingid = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        bookingidlabel1 = new javax.swing.JLabel();
        rewardsTotalLabel = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        JPanelIndBookingDetailsMain.setBackground(new java.awt.Color(0, 102, 102));
        JPanelIndBookingDetailsMain.setPreferredSize(new java.awt.Dimension(1460, 850));

        kGradientPanel1.setBackground(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(300, 1460));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel7.setText("Computer Parts Recycling System");
        jLabel7.setName(""); // NOI18N
        jLabel7.setOpaque(true);

        welcomeLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_rounded_left_50px.png"))); // NOI18N
        jButton7.setText("Logout");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );

        lbldropoffheader.setBackground(new java.awt.Color(204, 255, 204));
        lbldropoffheader.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lbldropoffheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldropoffheader.setText("View Booking History");
        lbldropoffheader.setOpaque(true);

        bookingidlabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bookingidlabel.setForeground(new java.awt.Color(255, 255, 255));
        bookingidlabel.setText("Enter Booking ID");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblPickUpBookingDetails.setAutoCreateRowSorter(true);
        tblPickUpBookingDetails.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        tblPickUpBookingDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Item ID", "Category", "Computer Parts", "Status", "Est. Rewards", "Make", "Model", "Added on", "Weight(lbs.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPickUpBookingDetails.setGridColor(new java.awt.Color(255, 255, 255));
        tblPickUpBookingDetails.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane1.setViewportView(tblPickUpBookingDetails);

        btnBack.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backarrow.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnBack.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(51, 51, 51));
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        bookingidlabel1.setBackground(new java.awt.Color(204, 255, 204));
        bookingidlabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        bookingidlabel1.setText("Total Estimated Rewards: ");
        bookingidlabel1.setOpaque(true);

        rewardsTotalLabel.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        rewardsTotalLabel.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout JPanelIndBookingDetailsMainLayout = new javax.swing.GroupLayout(JPanelIndBookingDetailsMain);
        JPanelIndBookingDetailsMain.setLayout(JPanelIndBookingDetailsMainLayout);
        JPanelIndBookingDetailsMainLayout.setHorizontalGroup(
            JPanelIndBookingDetailsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1460, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                .addGap(0, 713, Short.MAX_VALUE)
                .addGroup(JPanelIndBookingDetailsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                        .addComponent(btnsearch)
                        .addGap(623, 623, 623))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                        .addComponent(bookingidlabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rewardsTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                .addGroup(JPanelIndBookingDetailsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                        .addGap(770, 770, 770)
                        .addComponent(txtbookingid, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                        .addGap(572, 572, 572)
                        .addComponent(bookingidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldropoffheader, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(447, 447, 447))
            .addGroup(JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        JPanelIndBookingDetailsMainLayout.setVerticalGroup(
            JPanelIndBookingDetailsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelIndBookingDetailsMainLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldropoffheader, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelIndBookingDetailsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbookingid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(bookingidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsearch)
                .addGap(2, 2, 2)
                .addGroup(JPanelIndBookingDetailsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingidlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rewardsTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(JPanelIndBookingDetailsMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DB4OUtil.getInstance().storeSystem(this.ecosystem);
        MainJPanel main = new MainJPanel(JPanelIndBookingDetailsMain);
        CardLayout layout = (CardLayout) JPanelIndBookingDetailsMain.getLayout();
        JPanelIndBookingDetailsMain.add("Home", main);

        layout.next(JPanelIndBookingDetailsMain);
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try{
        String bookingId = txtbookingid.getText();
        if (!bookingId.equals("")) {
            populateTable(bookingId);
        }
        }
        catch(NullPointerException e)
        {}
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        JPanelIndBookingDetailsMain.remove(this);
        CardLayout layout = (CardLayout) JPanelIndBookingDetailsMain.getLayout();
        layout.previous(JPanelIndBookingDetailsMain);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateTable(String bookingId) {
        int totalRewards = 0;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DefaultTableModel model = (DefaultTableModel) tblPickUpBookingDetails.getModel();
        model.setRowCount(0);
        for (InventoryBooking booking: this.ecosystem.getBookingDirectory().getBookingsByResident(this.resident)){
            for (Item item: booking.getItems()) {
                Object[] row = new Object[11];
                int rewards = item.getRewardPoints();
                totalRewards+=rewards;
                if (!bookingId.equals("") && !bookingId.equals(booking.getId())) continue;
                row[0] = booking.getId();
                row[1] = item.getId();
                row[2] = item.getCategory();
                row[3] = item.getSubCategory();
                row[4] = item.getStatus().name();
                row[5] = rewards;
                row[6] = item.getMake();
                row[7] = item.getModel();
                row[8] = formatter.format(item.getRecievedOn());
                row[9] = item.getWeightApprox();
                model.addRow(row);
            }
        }
        rewardsTotalLabel.setText(String.valueOf(totalRewards));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelIndBookingDetailsMain;
    private javax.swing.JLabel bookingidlabel;
    private javax.swing.JLabel bookingidlabel1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbldropoffheader;
    private javax.swing.JLabel rewardsTotalLabel;
    private javax.swing.JTable tblPickUpBookingDetails;
    private javax.swing.JTextField txtbookingid;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
