/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.resident;

import UserInterface.resident.BookingHistoryJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import SystemModels.DB4OUtil.DB4OUtil;
import SystemModels.EcoSystem;
import SystemModels.User.Customer.Resident;
import UserInterface.MainJPanel;

/**
 *
 * @author Pranav Kashyap Komanduri
 */
public class LoginProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndiProfileLoginJPanel
     */
    JPanel jPanel2;
    EcoSystem ecosystem;
    Resident resident;
    public LoginProfileJPanel(JPanel mainJPanel, EcoSystem ecosystem, Resident resident) {
        this.JPanelIndLogin = mainJPanel;
        initComponents();
        this.ecosystem = ecosystem;
        this.resident = resident;
        nameLabel.setText(resident.getFullName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelIndLogin = new javax.swing.JPanel();
        JPanelIndLoginMain = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        btnviewdashboard = new javax.swing.JButton();
        btnviewbookingdetails = new javax.swing.JButton();
        btnviewprofile = new javax.swing.JButton();
        btnviewpickup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtprofile = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1460, 850));
        setLayout(new java.awt.CardLayout());

        JPanelIndLogin.setBackground(new java.awt.Color(255, 255, 255));
        JPanelIndLogin.setPreferredSize(new java.awt.Dimension(1460, 850));
        JPanelIndLogin.setLayout(new java.awt.CardLayout());

        JPanelIndLoginMain.setBackground(new java.awt.Color(0, 102, 102));
        JPanelIndLoginMain.setPreferredSize(new java.awt.Dimension(1460, 850));

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(300, 1460));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel7.setText("Computer Parts Recycling System");
        jLabel7.setOpaque(true);

        nameLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N

        logoutButton.setBackground(new java.awt.Color(204, 255, 204));
        logoutButton.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(51, 51, 51));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_rounded_left_50px.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(null);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btnviewdashboard.setBackground(new java.awt.Color(204, 255, 204));
        btnviewdashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/speed_127px.png"))); // NOI18N
        btnviewdashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnviewdashboard.setBorderPainted(false);
        btnviewdashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnviewdashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewdashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewdashboardMouseExited(evt);
            }
        });
        btnviewdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdashboardActionPerformed(evt);
            }
        });

        btnviewbookingdetails.setBackground(new java.awt.Color(204, 255, 204));
        btnviewbookingdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details_127px_1.png"))); // NOI18N
        btnviewbookingdetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnviewbookingdetails.setBorderPainted(false);
        btnviewbookingdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnviewbookingdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewbookingdetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewbookingdetailsMouseExited(evt);
            }
        });
        btnviewbookingdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbookingdetailsActionPerformed(evt);
            }
        });

        btnviewprofile.setBackground(new java.awt.Color(204, 255, 204));
        btnviewprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person_127px_2.png"))); // NOI18N
        btnviewprofile.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnviewprofile.setBorderPainted(false);
        btnviewprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnviewprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewprofileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewprofileMouseExited(evt);
            }
        });
        btnviewprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewprofileActionPerformed(evt);
            }
        });

        btnviewpickup.setBackground(new java.awt.Color(204, 255, 204));
        btnviewpickup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schedule_127px_1.png"))); // NOI18N
        btnviewpickup.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnviewpickup.setBorderPainted(false);
        btnviewpickup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnviewpickup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnviewpickupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnviewpickupMouseExited(evt);
            }
        });
        btnviewpickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpickupActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        txtprofile.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtprofile.setForeground(new java.awt.Color(255, 255, 255));
        txtprofile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtprofile.setText("My Profile");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("View Booking Details");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Create Pick-up booking");

        javax.swing.GroupLayout JPanelIndLoginMainLayout = new javax.swing.GroupLayout(JPanelIndLoginMain);
        JPanelIndLoginMain.setLayout(JPanelIndLoginMainLayout);
        JPanelIndLoginMainLayout.setHorizontalGroup(
            JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1455, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelIndLoginMainLayout.createSequentialGroup()
                .addGroup(JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelIndLoginMainLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnviewprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelIndLoginMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelIndLoginMainLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnviewpickup, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnviewbookingdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(btnviewdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(JPanelIndLoginMainLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel5)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(189, Short.MAX_VALUE))))
        );
        JPanelIndLoginMainLayout.setVerticalGroup(
            JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelIndLoginMainLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addGroup(JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnviewdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnviewbookingdetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnviewpickup, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelIndLoginMainLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnviewprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(JPanelIndLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        JPanelIndLogin.add(JPanelIndLoginMain, "card2");

        add(JPanelIndLogin, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
       DB4OUtil.getInstance().storeSystem(this.ecosystem);
        MainJPanel main = new MainJPanel(JPanelIndLogin);
        CardLayout layout = (CardLayout) JPanelIndLogin.getLayout();
        JPanelIndLogin.add("Home", main);

        layout.next(JPanelIndLogin);
        
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btnviewdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdashboardActionPerformed
        // TODO add your handling code here:
        ProfileDashboard indidashboard = new ProfileDashboard(JPanelIndLogin,ecosystem, resident);
        CardLayout layout = (CardLayout) JPanelIndLogin.getLayout();
        JPanelIndLogin.add("individualDashboardPanel", indidashboard);

        layout.next(JPanelIndLogin);
    }//GEN-LAST:event_btnviewdashboardActionPerformed

    private void btnviewbookingdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbookingdetailsActionPerformed
        // TODO add your handling code here:
        try{
        BookingHistoryJPanel indibookingdetails = new BookingHistoryJPanel(JPanelIndLogin,  ecosystem, resident);
        CardLayout layout = (CardLayout) JPanelIndLogin.getLayout();
        JPanelIndLogin.add("individualBookingDetails", indibookingdetails);

        layout.next(JPanelIndLogin);
        }
        catch(NullPointerException e){
        }
    }//GEN-LAST:event_btnviewbookingdetailsActionPerformed

    private void btnviewprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewprofileActionPerformed
        // TODO add your handling code here:

        DetailsProfileJPanel indiprofiledetails = new DetailsProfileJPanel(JPanelIndLogin,  ecosystem, resident);
        CardLayout layout = (CardLayout) JPanelIndLogin.getLayout();
        JPanelIndLogin.add("individualProfileDetails", indiprofiledetails);

        layout.next(JPanelIndLogin);
    }//GEN-LAST:event_btnviewprofileActionPerformed

    private void btnviewprofileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewprofileMouseEntered
        // TODO add your handling code here:
        btnviewprofile.setBorder(BorderFactory.createEtchedBorder(0));  
    }//GEN-LAST:event_btnviewprofileMouseEntered

    private void btnviewprofileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewprofileMouseExited
        // TODO add your handling code here:
        btnviewprofile.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnviewprofileMouseExited

    private void btnviewdashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewdashboardMouseEntered
        // TODO add your handling code here:
        btnviewdashboard.setBorder(BorderFactory.createEtchedBorder(0));  
    }//GEN-LAST:event_btnviewdashboardMouseEntered

    private void btnviewdashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewdashboardMouseExited
        // TODO add your handling code here:
        btnviewdashboard.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnviewdashboardMouseExited

    private void btnviewpickupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewpickupMouseEntered
        // TODO add your handling code here:
        btnviewpickup.setBorder(BorderFactory.createEtchedBorder(0));
    }//GEN-LAST:event_btnviewpickupMouseEntered

    private void btnviewpickupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewpickupMouseExited
        // TODO add your handling code here:
        btnviewpickup.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnviewpickupMouseExited

    private void btnviewbookingdetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewbookingdetailsMouseEntered
        // TODO add your handling code here:
        btnviewbookingdetails.setBorder(BorderFactory.createEtchedBorder(0));  
    }//GEN-LAST:event_btnviewbookingdetailsMouseEntered

    private void btnviewbookingdetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewbookingdetailsMouseExited
        // TODO add your handling code here:
        btnviewbookingdetails.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
    }//GEN-LAST:event_btnviewbookingdetailsMouseExited

    private void btnviewpickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpickupActionPerformed
        // TODO add your handling code here:
        PickUpProfileJPanel indipickupJPanel = new PickUpProfileJPanel(JPanelIndLogin, ecosystem, resident);
        CardLayout layout = (CardLayout) JPanelIndLogin.getLayout();
        JPanelIndLogin.add("individualpickupbooking", indipickupJPanel);

        layout.next(JPanelIndLogin);
    }//GEN-LAST:event_btnviewpickupActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        DB4OUtil.getInstance().storeSystem(this.ecosystem);
    }//GEN-LAST:event_logoutButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelIndLogin;
    private javax.swing.JPanel JPanelIndLoginMain;
    private javax.swing.JButton btnviewbookingdetails;
    private javax.swing.JButton btnviewdashboard;
    private javax.swing.JButton btnviewpickup;
    private javax.swing.JButton btnviewprofile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel txtprofile;
    // End of variables declaration//GEN-END:variables
}
